CREATE TABLE personas (
    cedula VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(30)
);

CREATE TABLE titulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(160) NOT NULL,
    universidad VARCHAR(160) NOT NULL,
    fecha_registro DATE NOT NULL,
    persona_cedula VARCHAR(10) NOT NULL,
    CONSTRAINT fk_titulos_persona
        FOREIGN KEY (persona_cedula)
        REFERENCES personas (cedula)
        ON DELETE CASCADE
);

CREATE INDEX idx_titulos_persona_cedula ON titulos (persona_cedula);
